name: Build ruleset and geodata
on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - ".github/workflows/delete-old-workflows.yml"
      - ".github/workflows/config.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> ${GITHUB_ENV}
          domains_list=$(curl -sSL https://api.github.com/repos/DustinWin/domain-list-custom/releases/latest | grep 'browser_download_url' | sed 's/.*\///' | sed 's/\..*//')
          ips_list=$(curl -sSL https://api.github.com/repos/DustinWin/geoip/releases/tags/ips | grep 'browser_download_url' | sed 's/.*\///' | sed 's/\..*//')
        shell: bash

      - name: Clone Repository
        uses: actions/checkout@master

      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: community

      - name: Checkout DustinWin/geoip
        uses: actions/checkout@v4
        with:
          repository: DustinWin/geoip
          ref: clash
          path: geoip/clash

      - name: Checkout DustinWin/geoip
        uses: actions/checkout@v4
        with:
          repository: DustinWin/geoip
          ref: sing-box
          path: geoip/sing-box

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: ./community/go.sum

      - name: Generate `clash` geodata
        run: |
          mkdir -p ./community/mydata/ ./tmp/

          # Generate `clash` geosite-all.dat
          for archs in ${domains_list}; do
            curl -sSL "https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/${archs}.list" | sed 's/^DOMAIN,/full:/' | sed 's/^DOMAIN-SUFFIX,//' | sed 's/^DOMAIN-KEYWORD,/keyword:/' >  "./tmp/${archs}.txt"
            cat "./tmp/${archs}.txt" > "./community/mydata/${archs}"
          done
          cd ./community/
          go run ./ --datapath=./mydata/ --outputname geosite-all.dat

          # Generate `clash` geosite-all-lite.dat
          rm -f ./mydata/ads
          go run ./ --datapath=./mydata/ --outputname geosite-all-lite.dat

          # Generate `clash` geosite.dat
          rm -f ./mydata/*
          for archs1 in ads private fakeip-filter microsoft-cn apple-cn google-cn games-cn networktest proxy cn; do
            curl -sSL "https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/${archs1}.list" | sed 's/^DOMAIN,/full:/' | sed 's/^DOMAIN-SUFFIX,//' | sed 's/^DOMAIN-KEYWORD,/keyword:/' > "./mydata/${archs1}"
          done
          go run ./ --datapath=./mydata/ --outputname geosite.dat

          # Generate `clash` geosite-lite.dat
          rm -f ./mydata/ads
          go run ./ --datapath=./mydata/ --outputname geosite-lite.dat

      - name: Generate `sing-box` geodata
        run: |
          cd ./community/ || exit 1
          go install -trimpath -ldflags="-s -w -buildid=" github.com/metacubex/geo/cmd/geo@master
          for file in $(ls *.dat | sed 's/\..*//'); do
            geo convert site -i v2ray -o sing -f "./${file}.db" "./${file}.dat"
          done

      - name: Move `clash` and `sing-box` geodata files
        run: |
          mkdir -p ./clash/ ./sing-box/
          cd ./community/ || exit 1
          for file in $(ls *.dat); do
            install -Dp "./${file}" ../clash/
          done
          for file in $(ls *.db); do
            install -Dp "./${file}" ../sing-box/
          done
          rm -rf ../community*

      - name: Get geoip relative files
        run: |
          cp -f ./geoip/clash/* ./clash/
          cp -f ./geoip/sing-box/* ./sing-box/
          rm -rf ./geoip*

      - name: Generate `clash` rule-set
        run: |
          domains_list=$(curl -sSL https://api.github.com/repos/DustinWin/domain-list-custom/releases/latest | grep 'browser_download_url' | sed 's/.*\///' | sed 's/\..*//')
          ips_list=$(curl -sSL https://api.github.com/repos/DustinWin/geoip/releases/tags/ips | grep 'browser_download_url' | sed 's/.*\///' | sed 's/\..*//')
          mkdir -p ./clash-ruleset/ ./sing-box-ruleset/

          # Generate `clash` rule-set (yaml)
          for archs in ${domains_list}; do
            echo 'payload:' > "./clash-ruleset/${archs}.yaml"
            curl -sSL "https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/${archs}.list" | grep -Ev 'DOMAIN-KEYWORD,|PROCESS-NAME,' | sed '/^\s*$/d' | sed "s/^DOMAIN,/  - '/" | sed "s/^DOMAIN-SUFFIX,/  - '+\./" | sed "s/$/'/" >> "./clash-ruleset/${archs}.yaml"
          done

          echo 'payload:' > ./clash-ruleset/applications.yaml
          curl -sSL https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/applications.list | sed 's/^/  - /' >> ./clash-ruleset/applications.yaml

          echo 'payload:' > ./clash-ruleset/networktest.yaml
          curl -sSL https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/networktest.list | sed 's/^/  - /' >> ./clash-ruleset/networktest.yaml

          for archs in ${ips_list}; do
            echo 'payload:' > "./clash-ruleset/${archs}.yaml"
            curl -sSL "https://raw.githubusercontent.com/DustinWin/geoip/ips/${archs}.list" | sed "s/^IP-CIDR,/  - '/" | sed "s/^IP-CIDR6,/  - '/" | sed "s/$/'/" >> "./clash-ruleset/${archs}.yaml"
          done

          # Generate `clash` rule-set (text)
          for archs in ${domains_list}; do
            curl -sSL "https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/${archs}.list" | grep -Ev 'DOMAIN-KEYWORD,|PROCESS-NAME,' | sed '/^\s*$/d' | sed 's/^DOMAIN,//' | sed 's/^DOMAIN-SUFFIX,/+\./' > "./clash-ruleset/${archs}.list"
          done

          curl -sSL https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/applications.list > ./clash-ruleset/applications.list
          curl -sSL https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/networktest.list > ./clash-ruleset/networktest.list

          for archs in ${ips_list}; do
            curl -sSL "https://raw.githubusercontent.com/DustinWin/geoip/ips/${archs}.list" | sed 's/^IP-CIDR,//' | sed 's/^IP-CIDR6,//' > "./clash-ruleset/${archs}.list"
          done

          # Ready for generate `sing-box` rule_set
          for archs in ${domains_list}; do
            mkdir -p "./tools/rules/${archs}/"
            curl "https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/${archs}.list" > "./tools/rules/${archs}/${archs}.yaml"
          done

          mkdir -p ./tools/rules/applications/ ./tools/rules/networktest/
          curl -sSL https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/applications.list > ./tools/rules/applications/applications.yaml
          curl -sSL https://raw.githubusercontent.com/DustinWin/domain-list-custom/domains/networktest.list > ./tools/rules/networktest/networktest.yaml

          for archs in ${ips_list}; do
            mkdir -p "./tools/rules/${archs}/"
            curl -sSL "https://raw.githubusercontent.com/DustinWin/geoip/ips/${archs}.list" > "./tools/rules/${archs}/${archs}.yaml"
          done

      - name: Download and unzip `sing-box core`
        run: |
          sing_box_version=$(curl -sSL https://api.github.com/repos/SagerNet/sing-box/releases | grep 'tag_name' | grep 'rc' | head -n 1 | sed 's/.*v//' | sed 's/".*//')
          wget "https://github.com/SagerNet/sing-box/releases/download/v${sing_box_version}/sing-box-${sing_box_version}-linux-amd64v3.tar.gz" -O - | tar -zxf - -C ./tools/
          cp -f ./tools/sing-box-${sing_box_version}-linux-amd64v3/sing-box ./tools/

      - name: Generate `sing-box` rule_set
        run: |
          cd ./tools/
          chmod +x convert.sh && ./convert.sh
          rm -rf ./sing-box* LICENSE ./rules*
          cp -f ./*.json ./*.srs ../sing-box-ruleset/
          rm -rf ./tmp*

      - name: Release and upload `clash` assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: clash
          tag: clash
          overwrite: true
          body: "[Clash](https://github.com/Dreamacro/clash) 规则集文件（包含 .dat、.mmdb 和 .metadb 文件）"
          file_glob: true
          file: ./clash/*

      - name: Git push assets to "clash" branch
        run: |
          cd ./clash/ || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b clash
          git add .
          git commit -m "Clash ruleset_geodata 文件更新于 ${update_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin clash

      - name: Commit and push `clash-ruleset` branch
        run: |
          cd ./clash-ruleset/ || exit 1
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b clash-ruleset
          git add . && git commit -m "Clash rule-set 规则集文件更新于 ${update_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin clash-ruleset

      - name: Release and upload `sing-box` assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: sing-box
          tag: sing-box
          overwrite: true
          body: "[sing-box](https://github.com/SagerNet/sing-box) 规则集文件（包含 .db 文件）"
          file_glob: true
          file: ./sing-box/*

      - name: Git push assets to "sing-box" branch
        run: |
          cd ./sing-box/ || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b sing-box
          git add .
          git commit -m "sing-box ruleset_geodata 文件更新于 ${update_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin sing-box

      - name: Commit and push `sing-box-ruleset` branch
        run: |
          cd ./sing-box-ruleset/ || exit 1
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b sing-box-ruleset
          git add . && git commit -m "sing-box rule_set 规则集文件更新于 ${update_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin sing-box-ruleset

      - name: Purge jsDelivr CDN
        run: |
          cd ./clash/ || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@clash/${file}"
          done
          cd ../clash-ruleset/ || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@clash-ruleset/${file}"
          done
          cd ../sing-box/ || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@sing-box/${file}"
          done
          cd ../sing-box-ruleset/ || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@sing-box-ruleset/${file}"
          done
